// This file has been generated by Py++.

#ifndef visiocyte_free_functions_hpp__pyplusplus_wrapper
#define visiocyte_free_functions_hpp__pyplusplus_wrapper

void register_free_functions();

#endif//visiocyte_free_functions_hpp__pyplusplus_wrapper
