// This file has been generated by Py++.

#include "boost/python.hpp"
#include "wrappable_visiocyte.h"
#include "VISIOCYTE_GlobalSetting.pypp.hpp"

namespace bp = boost::python;

void register_VISIOCYTE_GlobalSetting_class(){

    bp::class_< VISIOCYTE_GlobalSetting >( "VISIOCYTE_GlobalSetting", "\n General settings for the VISIOCYTE program.\n", bp::init< >() )    
        .def_readwrite( "GPara_df_compute_method", &VISIOCYTE_GlobalSetting::GPara_df_compute_method )    
        .def_readwrite( "GPara_landmarkMatchingMethod", &VISIOCYTE_GlobalSetting::GPara_landmarkMatchingMethod )    
        .def_readwrite( "autoVideoCardStreamMode", &VISIOCYTE_GlobalSetting::autoVideoCardStreamMode )    
        .def_readwrite( "b_3dcurve_autoconnecttips", &VISIOCYTE_GlobalSetting::b_3dcurve_autoconnecttips )    
        .def_readwrite( "b_3dcurve_autodeform", &VISIOCYTE_GlobalSetting::b_3dcurve_autodeform )    
        .def_readwrite( "b_3dcurve_autowidth", &VISIOCYTE_GlobalSetting::b_3dcurve_autowidth )    
        .def_readwrite( "b_3dcurve_inertia", &VISIOCYTE_GlobalSetting::b_3dcurve_inertia )    
        .def_readwrite( "b_3dcurve_width_from_xyonly", &VISIOCYTE_GlobalSetting::b_3dcurve_width_from_xyonly )    
        .def_readwrite( "b_UseMylibTiff", &VISIOCYTE_GlobalSetting::b_UseMylibTiff )    
        .def_readwrite( "b_autoConvert2_8bit", &VISIOCYTE_GlobalSetting::b_autoConvert2_8bit )    
        .def_readwrite( "b_autoDispBoundingBox", &VISIOCYTE_GlobalSetting::b_autoDispBoundingBox )    
        .def_readwrite( "b_autoDispXYZAxes", &VISIOCYTE_GlobalSetting::b_autoDispXYZAxes )    
        .def_readwrite( "b_autoOpenImg3DViewer", &VISIOCYTE_GlobalSetting::b_autoOpenImg3DViewer )    
        .def_readwrite( "b_autoRescale16bitDisplay", &VISIOCYTE_GlobalSetting::b_autoRescale16bitDisplay )    
        .def_readwrite( "b_autoSWCLineMode", &VISIOCYTE_GlobalSetting::b_autoSWCLineMode )    
        .def_readwrite( "b_autoVideoCard3DTex", &VISIOCYTE_GlobalSetting::b_autoVideoCard3DTex )    
        .def_readwrite( "b_autoVideoCardCompress", &VISIOCYTE_GlobalSetting::b_autoVideoCardCompress )    
        .def_readwrite( "b_autoVideoCardNPTTex", &VISIOCYTE_GlobalSetting::b_autoVideoCardNPTTex )    
        .def_readwrite( "b_plugin_dispParameterDialog", &VISIOCYTE_GlobalSetting::b_plugin_dispParameterDialog )    
        .def_readwrite( "b_plugin_dispResInNewWindow", &VISIOCYTE_GlobalSetting::b_plugin_dispResInNewWindow )    
        .def_readwrite( "b_plugin_outputImgConvert2UINT8", &VISIOCYTE_GlobalSetting::b_plugin_outputImgConvert2UINT8 )    
        .def_readwrite( "b_plugin_outputImgRescale", &VISIOCYTE_GlobalSetting::b_plugin_outputImgRescale )    
        .def_readwrite( "b_yaxis_up", &VISIOCYTE_GlobalSetting::b_yaxis_up, "\n General settings for the VISIOCYTE program.\n" )    
        .def_readwrite( "default_lookglass_size", &VISIOCYTE_GlobalSetting::default_lookglass_size )    
        .def_readwrite( "default_marker_radius", &VISIOCYTE_GlobalSetting::default_marker_radius )    
        .def_readwrite( "default_rightshift_bits", &VISIOCYTE_GlobalSetting::default_rightshift_bits )    
        .def_readwrite( "iChannel_for_plugin", &VISIOCYTE_GlobalSetting::iChannel_for_plugin )    
        .def_readwrite( "marker_disp_amplifying_factor", &VISIOCYTE_GlobalSetting::marker_disp_amplifying_factor );

}
