// This file has been generated by Py++.

#ifndef VISIOCYTEPluginArg_double3x3_hpp__pyplusplus_wrapper
#define VISIOCYTEPluginArg_double3x3_hpp__pyplusplus_wrapper

void register_VISIOCYTEPluginArg_double3x3_class();

#endif//VISIOCYTEPluginArg_double3x3_hpp__pyplusplus_wrapper
