// This file has been generated by Py++.

#include "boost/python.hpp"
#include "wrappable_visiocyte.h"
#include "VISIOCYTEPluginArg_double3x3.pypp.hpp"

namespace bp = boost::python;

void register_VISIOCYTEPluginArg_double3x3_class(){

    bp::class_< VISIOCYTEPluginArg< c_array< c_array< double, 3 >, 3 > >, bp::bases< VISIOCYTEPluginArgItem > >( "VISIOCYTEPluginArg_double3x3", bp::init< c_array< c_array< double, 3 >, 3 > &, std::string const & >(( bp::arg("item"), bp::arg("typeName") )) )    
        .def( 
            "getItem"
            , (::c_array< c_array< double, 3 >, 3 > const & ( ::VISIOCYTEPluginArg<c_array<c_array<double, 3>, 3> >::* )(  ) const)( &::VISIOCYTEPluginArg< c_array< c_array< double, 3 >, 3 > >::getItem )
            , bp::return_value_policy< bp::copy_const_reference >() )    
        .def( 
            "getType"
            , (::std::string ( ::VISIOCYTEPluginArg<c_array<c_array<double, 3>, 3> >::* )(  ) const)( &::VISIOCYTEPluginArg< c_array< c_array< double, 3 >, 3 > >::getType ) )    
        .def( 
            "setItem"
            , (void ( ::VISIOCYTEPluginArg<c_array<c_array<double, 3>, 3> >::* )( ::c_array< c_array< double, 3 >, 3 > & ) )( &::VISIOCYTEPluginArg< c_array< c_array< double, 3 >, 3 > >::setItem )
            , ( bp::arg("item") ) )    
        .def( 
            "setType"
            , (void ( ::VISIOCYTEPluginArg<c_array<c_array<double, 3>, 3> >::* )( ::std::string const & ) )( &::VISIOCYTEPluginArg< c_array< c_array< double, 3 >, 3 > >::setType )
            , ( bp::arg("s") ) );

}
