// This file has been generated by Py++.

#ifndef VISIOCYTE_GlobalSetting_hpp__pyplusplus_wrapper
#define VISIOCYTE_GlobalSetting_hpp__pyplusplus_wrapper

void register_VISIOCYTE_GlobalSetting_class();

#endif//VISIOCYTE_GlobalSetting_hpp__pyplusplus_wrapper
