// This file has been generated by Py++.

#ifndef VISIOCYTEPluginArgItem_hpp__pyplusplus_wrapper
#define VISIOCYTEPluginArgItem_hpp__pyplusplus_wrapper

void register_VISIOCYTEPluginArgItem_class();

#endif//VISIOCYTEPluginArgItem_hpp__pyplusplus_wrapper
