// This file has been generated by Py++.

#ifndef visiocyte_global_variables_hpp__pyplusplus_wrapper
#define visiocyte_global_variables_hpp__pyplusplus_wrapper

void register_global_variables();

#endif//visiocyte_global_variables_hpp__pyplusplus_wrapper
