// This file has been generated by Py++.

#ifndef visiocyte_enumerations_hpp__pyplusplus_wrapper
#define visiocyte_enumerations_hpp__pyplusplus_wrapper

void register_enumerations();

#endif//visiocyte_enumerations_hpp__pyplusplus_wrapper
